export const techsList = {
  roles: ["Front-end", "Back-end", "FullStack", "DevOps", "Mobile"],
  frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Angular",
    "Vue.js",
    "jQuery",
    "Bootstrap",
    "Sass",
    "Less",
    "Ember.js",
    "Backbone.js",
    "Materialize",
    "Foundation",
    "Bulma",
  ],
  backend: [
    "Node.js",
    "Java",
    "Python",
    "Ruby on Rails",
    "ASP.NET",
    "PHP",
    "Django",
    "Spring Boot",
    "Express",
    "Flask",
    "Laravel",
    "Symfony",
    "Golang",
    "C#/.NET",
    "Scala",
  ],
  devops: [
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "IBM Cloud",
    "Oracle Cloud",
    "Alibaba Cloud",
    "DigitalOcean",
    "Heroku",
    "Rackspace",
    "OpenStack",
    "VMware Cloud",
    "Salesforce Cloud",
    "Red Hat OpenShift",
    "Cisco CloudCenter",
    "SAP Cloud Platform",
  ],
  mobile: [
    "React Native",
    "Flutter",
    "Ionic",
    "Xamarin",
    "PhoneGap/Cordova",
    "NativeScript",
    "jQuery Mobile",
    "Mobile Angular UI",
    "Onsen UI",
    "Intel XDK",
  ],
  fullstack: ["teste"],
};
